/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "in1_aliases.h"
#include "in1.h"
#include "PwmPIN1_aliases.h"
#include "PwmPIN1.h"
#include "ClockPWM.h"
#include "PWM1.h"
#include "ADC_SAR_1.h"
#include "Pin_ADC_in_aliases.h"
#include "Pin_ADC_in.h"
#include "Clock_10kHz.h"
#include "Control_Reg.h"
#include "Counter_INT.h"
#include "Counter.h"
#include "Timer.h"
#include "Timer_INT.h"
#include "Clock_100kHz.h"
#include "SensorOut_aliases.h"
#include "SensorOut.h"
#include "in2_aliases.h"
#include "in2.h"
#include "PWM2.h"
#include "ClockPWM_1.h"
#include "PwmPIN2_aliases.h"
#include "PwmPIN2.h"
#include "in3_aliases.h"
#include "in3.h"
#include "in4_aliases.h"
#include "in4.h"
#include "S0_aliases.h"
#include "S0.h"
#include "S1_aliases.h"
#include "S1.h"
#include "S2_aliases.h"
#include "S2.h"
#include "S3_aliases.h"
#include "S3.h"
#include "OE_aliases.h"
#include "OE.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_ExtVref_aliases.h"
#include "ADC_SAR_1_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

